- name: web
  hosts: all
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: present
  - name: start httpd
    service:
      name: httpd
      state: started
      enabled: yes
  - name: copy
    become: true
    copy:
      src: index.html
      dest: /var/www/html/index.html
      backup: yes
  - name: restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes
