- name: server
  hosts: webservers
  become: yes
  tasks:
  - name: install httpd
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: start httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
  - name: install mysql
    ansible.builtin.yum:
      name: mysql
      state: present
